# site settings
title: TSS
subtitle: Consulting Co.
email: tssconsultingco@gmail.com
description: We are TSS Consulting Co. Our passion point is being the tech arm for small businesses. Our strengths are in consulting, design, code, and brainstorming. We'll see you soon!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: A Coffeeshop Near You
city: Chicago
state: IL
zip_code: 
country: USA
phone: (312) 291-1136

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url: https://facebook.com/tssconsulting.co
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/tssconsultingco
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/tssconsultingco

# build settings
markdown: kramdown

sass:
  style: compressed
